server:
  port: 8082

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/job-offers
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

offer:
  http:
    scheduler:
      request:
        delay: PT3H
    client:
      config:
        connectionTimeout: 1000
        port: 5057
        readTimeout: 1000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com

scheduling:
  enabled: true

auth:
  jwt:
    secretKey: ${JWT_SECRET}
    expirationDays: 30
    issuer: job-offers-backend