server:
  port: 8080

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

offer:
  http:
    scheduler:
      request:
        delay: PT1s
    client:
      config:
        connectionTimeout: 5000
        port: 5057
        readTimeout: 5000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com

scheduling:
  enabled: true

auth:
  jwt:
    secretKey: ${JWT_SECRET}
    expirationDays: 30
    issuer: job-offers-backend